version: '2'

services:
  confluence:
    image: teamatldocker/confluence
    container_name: confluence
    hostname: confluence
    networks:
      - confluencenet
    volumes:
      - confluencedata:/var/atlassian/confluence
    ports:
      - '80:8090'
      - '8091:8091'
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx2g'
      - 'JVM_MAXIMUM_MEMORY=2048m' # https://community.atlassian.com/t5/Confluence-questions/Error-on-upgrade-to-7-9-ERROR-relation-quot-confzdu-quot-does/qaq-p/1536936
      - 'CONFLUENCE_PROXY_NAME='
      - 'CONFLUENCE_PROXY_PORT='
      - 'CONFLUENCE_PROXY_SCHEME='
      - 'CONFLUENCE_DELAYED_START='

  postgresql:
    image: postgres:11.13-alpine
    container_name: postgres
    hostname: postgres
    networks:
      - confluencenet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=confluencedb'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=confluencedb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'

volumes:
  confluencedata:
    external: false
  postgresqldata:
    external: false

networks:
  confluencenet:
    driver: bridge
